const { app } = require('./utils/app')
const productsRouter = require('./routers/productsRouter')
const viewsRouter = require('./routers/viewsRouter')
const usersRouter = require('./routers/usersRouter')
const sessionRouter = require('./routers/sessionRouter')
const cartsRouter = require('./routers/cartsRouter')

app.use('/api/products', productsRouter)
app.use('/api/users', usersRouter)
app.use('/api/sessions', sessionRouter)
app.use('/api/carts', cartsRouter)
app.use('/', viewsRouter)